dbt_handson:
  target: snowflake
  outputs:
    snowflake:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: dbt_handson_db
      schema: "{{ env_var('DBT_SCHEMA', 'dev') }}"
      warehouse: dbt_handson_wh
      threads: 8
